name: flutter_unit_test_masterclass
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # mocktail is a mocking framework for Dart.
  mocktail: ^1.0.4

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
